apiVersion: v2
appVersion: "3.2.0"
description: A Helm chart for the deployment of WSO2 API Manager Pattern 1 (HA All-In-One Deployment with Analytics)
name: am-pattern-1
version: 3.2.0-3
icon: https://wso2.cachefly.net/wso2/sites/all/images/wso2logo.svg
type: application

